export const addressData = {
    countries: ['India', 'USA', 'Canada', 'UK', 'Australia', 'Germany'] as string[],
    statesByCountry: {
        India: ['Maharashtra', 'Karnataka', 'Delhi'],
        USA: ['California', 'Texas', 'New York'],
        Canada: ['Ontario', 'Quebec', 'Alberta'],
        UK: ['England', 'Scotland', 'Wales'],
        Australia: ['New South Wales', 'Victoria', 'Queensland'],
        Germany: ['Bavaria', 'Berlin', 'Hamburg'],
    } as Record<string, string[]>,
    citiesByState: {
        Maharashtra: ['Mumbai', 'Pune', 'Nagpur'],
        Karnataka: ['Bangalore', 'Mysore', 'Mangalore'],
        Delhi: ['New Delhi', 'Dwarka', 'Rohini'],
        California: ['Los Angeles', 'San Francisco', 'San Diego'],
        Texas: ['Austin', 'Houston', 'Dallas'],
        'New York': ['New York City', 'Buffalo', 'Albany'],
        Ontario: ['Toronto', 'Ottawa', 'Hamilton'],
        Quebec: ['Montreal', 'Quebec City', 'Laval'],
        Alberta: ['Calgary', 'Edmonton', 'Red Deer'],
        England: ['London', 'Manchester', 'Birmingham'],
        Scotland: ['Edinburgh', 'Glasgow', 'Aberdeen'],
        Wales: ['Cardiff', 'Swansea', 'Newport'],
        'New South Wales': ['Sydney', 'Newcastle', 'Wollongong'],
        Victoria: ['Melbourne', 'Geelong', 'Ballarat'],
        Queensland: ['Brisbane', 'Gold Coast', 'Cairns'],
        Bavaria: ['Munich', 'Nuremberg', 'Augsburg'],
        Berlin: ['Berlin City'],
        Hamburg: ['Hamburg City'],
    } as Record<string, string[]>,
    zipByCity: {
        Mumbai: '400001',
        Pune: '411001',
        Nagpur: '440001',
        Bangalore: '560001',
        Mysore: '570001',
        Mangalore: '575001',
        'New Delhi': '110001',
        Dwarka: '110075',
        Rohini: '110085',
        'Los Angeles': '90001',
        'San Francisco': '94101',
        'San Diego': '92101',
        Austin: '73301',
        Houston: '77001',
        Dallas: '75001',
        'New York City': '10001',
        Buffalo: '14201',
        Albany: '12201',
        Toronto: 'M5H',
        Ottawa: 'K1A',
        Hamilton: 'L8P',
        Montreal: 'H1A',
        'Quebec City': 'G1A',
        Laval: 'H7A',
        Calgary: 'T1Y',
        Edmonton: 'T5A',
        'Red Deer': 'T4N',
        London: 'EC1A',
        Manchester: 'M1',
        Birmingham: 'B1',
        Edinburgh: 'EH1',
        Glasgow: 'G1',
        Aberdeen: 'AB10',
        Cardiff: 'CF10',
        Swansea: 'SA1',
        Newport: 'NP20',
        Sydney: '2000',
        Newcastle: '2300',
        Wollongong: '2500',
        Melbourne: '3000',
        Geelong: '3220',
        Ballarat: '3350',
        Brisbane: '4000',
        'Gold Coast': '4217',
        Cairns: '4870',
        Munich: '80331',
        Nuremberg: '90402',
        Augsburg: '86150',
        'Berlin City': '10115',
        'Hamburg City': '20095',
    } as Record<string, string>,
    countryDialCodes: {
        India: "+91",
        USA: "+1",
        Canada: "+1",
        UK: "+44",
        Australia: "+61",
        Germany: "+49",
    } as Record<string, string>,
};
